apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: projectNameEnv
commonLabels:
  app: serviceNameEnv
  app.kubernetes.io/name: projectNameEnv
  app.kubernetes.io/version: v1
resources:
  - ../../base
patchesStrategicMerge:
  - configmap.yaml
  - secret.yaml