apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: serviceNameEnv
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: serviceNameEnv
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
  - type: Resource
    resource:
      name: memory
      targetAverageValue: 800Mi
