apiVersion: v1
kind: Secret
metadata:
  name: registry
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://cd-harbor.yunwdh.cn": {
          "username": "admin",
          "password": "Harbor12345"
        }
      }
    } 
type: kubernetes.io/dockerconfigjson